language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

stages:
  - lint
  - test

script:
  - cargo build --verbose
  - cargo test --verbose

jobs:
  include:
    - stage: lint
      rust: nightly
      script:
        - export PATH="$PATH:$HOME/.cargo/bin"
        - which rustfmt || cargo install rustfmt-nightly
        - cargo fmt -- --check

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
