language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

stages:
  - lint
  - test

script:
  - cargo build --verbose
  - cargo test --verbose

jobs:
  include:
    - stage: lint
      rust: nightly
      script:
        - export PATH="$PATH:~/.cargo/bin"
        - cargo +nightly install rustfmt-nightly --force
        - cargo +nightly fmt --all -- --check

matrix:
  allow_failures:
    - rust: nightly
      stage: test
  fast_finish: true
