[package]
name = "graphql-id"
version = "0.1.0"
authors = ["Boopathi Rajaa <me@boopathi.in>"]

[dependencies]
graphql-parser = "0.2.2"
rust-crypto = "0.2.36"
clap = "2.32.0"
itertools = "0.7.8"

[lib]
name = "graphql_id"
path = "src/lib.rs"

[[bin]]
name = "graphql-id"
path = "src/bin.rs"
