[package]
name = "graphql-id"
version = "0.1.0"
authors = ["Boopathi Rajaa <me@boopathi.in>"]

[dependencies]
graphql-parser = "0.2.2"

[lib]
name = "graphql_id"
path = "src/lib.rs"

[[bin]]
name = "graphql-id"
path = "src/bin.rs"
